# Dependencies
markdown:         redcarpet
#highlighter:      pygments

# Plugins
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            'Open Developer Blog'
tagline:          'Open Developer Blog'
description:      'My developer blog'
url:              http://blog.quentinmachard.fr
baseurl:          /

author:
  name:           'Quentin Machard'
  url:            https://www.quentinmachard.fr

paginate:         5

# Custom vars
#version:          2.1.0
