source: .
destination: ../dist

title:             Quentin Machard | Blog
title_display:     Quentin Machard
email:             quentin.machard@gmail.com
description:       LE BLOG
author:            Quentin Machard
baseurl:           "/"
url:               "http://blog.quentinmachard.fr"

# Social Profiles
twitter_username:  quentinmachard
github_username:   qmachard
website_url:       http://www.quentinmachard.fr

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
highlighter:       rouge
tag_page_layout: tag
tag_page_dir: tags
extlinks:
  attributes:
    rel: nofollow
    target: _blank
    class: external-link
  rel_exclude:     []
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-extlinks
  - jekyll-seo-tag

analytics:         UA-120870313-1
disqus:            https://quentin-machard-blog.disqus.com/embed.js

twitter:
  username: quentinmachard
  card: summary
